"Task 1"
name = input("Enter the name: ")
surname = input("Enter the surname: ")
phone_number = input("Enter the phone number: ")
street = input("Enter the street: ")
house_number = input("Enter the house number: ")
apartment_number = input("Enter the apartment number: ")
sity = input("Enter the name of sity: ")
index = input("Enter the index: ")
country = input("Enter the country: ")
print(name, surname)
print(phone_number)
print('Str.%s, %s, ap.%s, %s' % (street, house_number, apartment_number, sity))
print(index)
print(country)